sudo: required
services:
  - docker

before_install:
  - docker build -t h3llr4iser/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run h3llr4iser/react-test npm test -- --coverage

after_success:
  - docker build -t h3llr4iser/multi-client ./client
  - docker build -t h3llr4iser/multi-nginx ./nginx
  - docker build -t h3llr4iser/multi-server ./server
  - docker build -t h3llr4iser/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push h3llr4iser/multi-client
  - docker push h3llr4iser/multi-nginx
  - docker push h3llr4iser/multi-server
  - docker push h3llr4iser/multi-worker



