sudo: required
services:
  - docker

before_install:
  - docker build -t h3llr4iser/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run h3llr4iser/react-test npm test -- --coverage

after_success:
  - docker build -t h3llr4iser/multi-client ./client
  - docker build -t h3llr4iser/multi-nginx ./nginx
  - docker build -t h3llr4iser/multi-server ./server
  - docker build -t h3llr4iser/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push h3llr4iser/multi-client
  - docker push h3llr4iser/multi-nginx
  - docker push h3llr4iser/multi-server
  - docker push h3llr4iser/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-725101668907"
  bucket_path: "multi-docker"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
